kind: Pod
apiVersion: v1
metadata:
 name: ammi
 annotations:
  github.url: https://github.com/SudheerVadrevu/k8-resources-1.git
  # mostly annotations we use for special characters and getting external resources
spec:
  containers:
  - name: nginx
    image: nginx
